from .nodes import NODE_CLASS_MAPPINGS as BASE_NODE_CLASS_MAPPINGS
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as BASE_NODE_DISPLAY_NAME_MAPPINGS
from .smart_wan_first_middle_last_high_noise_end import (
    NODE_CLASS_MAPPINGS as WAN_NODE_CLASS_MAPPINGS,
)
from .smart_wan_first_middle_last_high_noise_end import (
    NODE_DISPLAY_NAME_MAPPINGS as WAN_NODE_DISPLAY_NAME_MAPPINGS,
)
from .smart_mobius_wan_loop import (
    NODE_CLASS_MAPPINGS as MOBIUS_NODE_CLASS_MAPPINGS,
)
from .smart_mobius_wan_loop import (
    NODE_DISPLAY_NAME_MAPPINGS as MOBIUS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .smart_painter_flf2v import (
    NODE_CLASS_MAPPINGS as PAINTER_NODE_CLASS_MAPPINGS,
)
from .smart_painter_flf2v import (
    NODE_DISPLAY_NAME_MAPPINGS as PAINTER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .smart_painter_long_video import (
    NODE_CLASS_MAPPINGS as PAINTER_LONG_NODE_CLASS_MAPPINGS,
)
from .smart_painter_long_video import (
    NODE_DISPLAY_NAME_MAPPINGS as PAINTER_LONG_NODE_DISPLAY_NAME_MAPPINGS,
)
from .smart_text_encode_edit_advanced import (
    NODE_CLASS_MAPPINGS as TEEA_NODE_CLASS_MAPPINGS,
)
from .smart_text_encode_edit_advanced import (
    NODE_DISPLAY_NAME_MAPPINGS as TEEA_NODE_DISPLAY_NAME_MAPPINGS,
)
from .smart_minimax_h3_single_frame_decoder import (
    NODE_CLASS_MAPPINGS as H3_STILL_NODE_CLASS_MAPPINGS,
)
from .smart_minimax_h3_single_frame_decoder import (
    NODE_DISPLAY_NAME_MAPPINGS as H3_STILL_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **BASE_NODE_CLASS_MAPPINGS,
    **WAN_NODE_CLASS_MAPPINGS,
    **MOBIUS_NODE_CLASS_MAPPINGS,
    **PAINTER_NODE_CLASS_MAPPINGS,
    **PAINTER_LONG_NODE_CLASS_MAPPINGS,
    **TEEA_NODE_CLASS_MAPPINGS,
    **H3_STILL_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **BASE_NODE_DISPLAY_NAME_MAPPINGS,
    **WAN_NODE_DISPLAY_NAME_MAPPINGS,
    **MOBIUS_NODE_DISPLAY_NAME_MAPPINGS,
    **PAINTER_NODE_DISPLAY_NAME_MAPPINGS,
    **PAINTER_LONG_NODE_DISPLAY_NAME_MAPPINGS,
    **TEEA_NODE_DISPLAY_NAME_MAPPINGS,
    **H3_STILL_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "js"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']

print("\033[34mSmart Helper Nodes: \033[92mLoaded\033[0m") 